import Head from "next/head";
import { useState } from "react";
import Image from "next/image";
import { Component } from "react/cjs/react.production.min";
import Label from "../components/Label";
import SubLabel from "../components/subLabel";
import Layout from "../components/Layout";
import styles from "../styles/Home.module.css";

export default function Home() {
  return (
    <Layout>
      <div className={styles.container}>
        <Head>
          <title>Create Next App</title>
          <meta name="description" content="Generated by create next app" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
      </div>
    </Layout>
  );
}
